// <auto-generated />
using System;
using AgroAlert.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AgroAlert.Infrastructure.Migrations
{
    [DbContext(typeof(AgroAlertDbContext))]
    [Migration("20260602021930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroAlert.Domain.Entities.Agricultor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AGRICULTORES", (string)null);
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEITURA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<bool>("Lido")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("LIDO");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_RISCO");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TipoAlerta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO_ALERTA");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("ALERTAS", (string)null);
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.DadoClimatico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<string>("FonteDados")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FONTE_DADOS");

                    b.Property<double>("Precipitacao")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PRECIPITACAO");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("Temperatura")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("TEMPERATURA");

                    b.Property<double>("Umidade")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("UMIDADE");

                    b.Property<double>("VelocidadeVento")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VELOCIDADE_VENTO");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("DADOS_CLIMATICOS", (string)null);
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.HistoricoAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ACAO");

                    b.Property<int>("AgricultorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<string>("EnderecoIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ENDERECO_IP");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("SUCESSO");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId");

                    b.ToTable("HISTORICO_ACESSO", (string)null);
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgricultorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("AreaHectares")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("AREA_HECTARES");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("TipoCultura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_CULTURA");

                    b.HasKey("Id");

                    b.HasIndex("AgricultorId");

                    b.ToTable("PROPRIEDADES", (string)null);
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.RegraAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVA");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("NivelRisco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOME");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("OPERADOR");

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PARAMETRO");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TipoAlerta")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("ValorLimite")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VALOR_LIMITE");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("REGRAS_ALERTA", (string)null);
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("AgroAlert.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany("Alertas")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.DadoClimatico", b =>
                {
                    b.HasOne("AgroAlert.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany("DadosClimaticos")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.HistoricoAcesso", b =>
                {
                    b.HasOne("AgroAlert.Domain.Entities.Agricultor", "Agricultor")
                        .WithMany("HistoricoAcessos")
                        .HasForeignKey("AgricultorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agricultor");
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.Propriedade", b =>
                {
                    b.HasOne("AgroAlert.Domain.Entities.Agricultor", "Agricultor")
                        .WithMany("Propriedades")
                        .HasForeignKey("AgricultorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agricultor");
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.RegraAlerta", b =>
                {
                    b.HasOne("AgroAlert.Domain.Entities.Propriedade", "Propriedade")
                        .WithMany("RegrasAlerta")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.Agricultor", b =>
                {
                    b.Navigation("HistoricoAcessos");

                    b.Navigation("Propriedades");
                });

            modelBuilder.Entity("AgroAlert.Domain.Entities.Propriedade", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("DadosClimaticos");

                    b.Navigation("RegrasAlerta");
                });
#pragma warning restore 612, 618
        }
    }
}
